#!/usr/bin/env bash
# Stops the 4-to_infinity_and_beyond process

# Find the PID(s) of the script named "4-to_infinity_and_beyond"
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Kill the process if it exists
if [ -n "$pid" ]; then
    kill "$pid"
fi
